const PATH_PREFIX = '../../../assets/'

export default {
  spinIcon: require(`${PATH_PREFIX}spinIcon.png`),
  spinLogo: require(`${PATH_PREFIX}spinLogo.png`),
  confettiBackground: require(`${PATH_PREFIX}confettiBackground.png`),
  checkIcon: require(`${PATH_PREFIX}checkIcon.png`),
  instagram: require(`${PATH_PREFIX}instagram.png`),
  twitter: require(`${PATH_PREFIX}twitter.png`),
  link: require(`${PATH_PREFIX}link.png`),
  facebook: require(`${PATH_PREFIX}facebook.png`),
  linkedIn: require(`${PATH_PREFIX}linkedIn.png`),
  spinButton: require(`${PATH_PREFIX}spinButton.png`),
  wheel: require(`${PATH_PREFIX}wheel.png`),
  starIcon: require(`${PATH_PREFIX}starIcon.png`),
  wheelIcon: require(`${PATH_PREFIX}wheelIcon.png`),
  giftIcon: require(`${PATH_PREFIX}giftIcon.png`),
  ticketIcon: require(`${PATH_PREFIX}ticketIcon.png`),
  wheelForeground: require(`${PATH_PREFIX}wheelForeground.png`),
  wheelBackground: require(`${PATH_PREFIX}wheelBackground.png`),
  wheelArrow: require(`${PATH_PREFIX}wheelArrow.png`),
  wheelRewardIcon: require(`${PATH_PREFIX}wheelRewardIcon.png`),
  closeIcon: require(`${PATH_PREFIX}closeIcon.png`),
  backIcon: require(`${PATH_PREFIX}backIcon.png`),
}